export const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
export const site = {
  name: 'EDIT Saffron',
  team: 'FTC Team 22310',
  url: 'https://22310.ca/',
  description: 'EDIT Saffron is FTC Team 22310 from Greater Sudbury, Ontario: student-built robots, programming, engineering, outreach, and competition at Lo-Ellen Park.',
  logo: 'https://22310.ca/assets/saffron-logo-2026.png?v=1',
  logoAlt: 'Red saffron flower and FTC team number 22310',
  email: 'team@22310.ca',
  school: 'Lo-Ellen Park Secondary School',
  city: 'Greater Sudbury',
  region: 'Ontario',
  country: 'CA'
};
const chevron = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m9 5 7 7-7 7" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const icons = {
  design:'<path d="m12 3 9 5-9 5-9-5 9-5ZM3 8v9l9 5 9-5V8M12 13v9"/>',
  automation:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',
  reach:'<path d="M3 11v5h4l10 4V4L7 8H3v3Zm4 5 2 6h4l-2-5M21 8v8"/>',
  trades:'<path d="m14 6-4 4 4 4 4-4m-8 0-7 7a2.8 2.8 0 0 0 4 4l7-7M14 6c0-3 3-5 6-4l-3 3 2 2 3-3c1 3-1 6-4 6"/>',
  strategy:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="M12 1v4m0 14v4M1 12h4m14 0h4"/>'
};
export const disciplines = [
  {id:'design',name:'Design',line:'From idea to mechanism.',description:'Sketch, model, prototype. Then make it better.',people:['Zavier S','Jett G']},
  {id:'automation',name:'Automation',line:'Bringing the robot to life.',description:'Code, controls, and the next autonomous run.',people:['Mirko R','Eden K','Alex L']},
  {id:'reach',name:'Reach',line:'Robotics, beyond the workshop.',description:'Sharing our work and connecting with our community.',people:['Ohm P','Devun P']},
  {id:'trades',name:'Trades',line:'Where the ideas take shape.',description:'Fabrication, assembly, wiring, and hands-on problem solving.',people:['Cameron G','Harlan P','John L']},
  {id:'strategy',name:'Strategy',line:'A plan for every match.',description:'Scouting the field and finding our next advantage.',people:['Xiaoqi M']},
];
const icon=id=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[id]}</svg>`;
const navItems=[['','Home'],['team','Team'],['events','Events'],['contact','Contact']];
export const brand=`<img src="/assets/saffron-logo-2026.png?v=1" width="42" height="42" alt=""/><span>EDIT Saffron<small>FTC team 22310</small></span>`;
export function navigation(active){return `<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="EDIT Saffron home">${brand}</a><nav class="site-nav" id="navigation" aria-label="Main navigation">${navItems.map(([id,label])=>`<a href="/${id?`${id}/`:''}" ${id===active?'aria-current="page"':''}>${label}</a>`).join('')}</nav><a class="login-link" href="https://team.22310.ca">Workspace ${arrow}</a><button class="menu-button" aria-label="Open menu" aria-controls="navigation" aria-expanded="false"><span></span><span></span></button></header>`;}
export const contactCTA=`<section class="contact-cta"><div class="section-inner"><div><span class="section-kicker">Let’s connect</span><h2>Talk to<br>the team.</h2></div><a class="round-link" href="/contact/" aria-label="Contact the team">${arrow}</a></div></section>`;
export const footer=`<footer class="site-footer"><div class="footer-main"><a class="brand" href="/" aria-label="EDIT Saffron home">${brand}</a><nav aria-label="Footer">${navItems.slice(1).map(([id,label])=>`<a href="/${id}/">${label}</a>`).join('')}<a href="https://team.22310.ca">Workspace ${arrow}</a></nav></div><div class="footer-bottom"><p>Lo-Ellen Park Secondary School<br>Greater Sudbury, Ontario</p><p>© ${new Date().getFullYear()} EDIT Saffron · FTC 22310</p><p>Independent FIRST® Tech Challenge team.<br>FIRST® and BIOBUZZ™ are trademarks of FIRST.</p></div></footer>`;
const loadingEvents='<div class="event-loading" role="status"><span></span>Loading events…</div>';
const eventDialog=`<dialog class="event-dialog" id="event-dialog" aria-labelledby="event-detail-title"><button class="dialog-close" aria-label="Close event">×</button><span class="section-kicker" id="event-detail-category"></span><h2 id="event-detail-title"></h2><p id="event-detail-time"></p><p id="event-detail-location"></p><button class="button" id="event-detail-save">Add to calendar ${arrow}</button></dialog>`;
export const pages={
  '':{
    title:'EDIT Saffron · FTC Team 22310',description:'EDIT Saffron is FTC Team 22310 from Greater Sudbury, Ontario: student-built robots, programming, engineering, outreach, and competition at Lo-Ellen Park.',type:'WebPage',
    body:`<main id="main"><section class="hero"><div class="hero-glow" aria-hidden="true"></div><div class="hero-inner"><div class="hero-copy"><h1><span>EDIT</span>Saffron<span class="brand-period">.</span></h1><p>Student-built robots. Shared ambition.<br>FIRST Tech Challenge · Greater Sudbury.</p><a class="button" href="/team/">Meet our team ${arrow}</a></div><div class="hero-emblem"><img src="/assets/saffron-logo-2026.png?v=1" width="1000" height="1000" alt="Red saffron flower above team number 22310" fetchpriority="high" decoding="async"/></div></div><a class="hero-scroll" href="#team">Discover Saffron <span aria-hidden="true">↓</span></a></section>
    <section class="team-preview section" id="team"><div class="section-inner team-overview"><div class="section-intro reveal"><span class="section-kicker">Our team</span><h2>Five disciplines.<br>One Saffron.</h2><p>We design, build, and compete together at Lo-Ellen Park Secondary School.</p><a class="text-link" href="/team/">Meet everyone ${arrow}</a><div class="mascot-scene"><div class="mascot-stage"><img class="mascot-fallback" src="/assets/mascot-fallback.svg" width="700" height="650" alt="Saffron’s friendly robot mascot and rover"/><canvas id="robot" tabindex="0" aria-label="Saffron robot mascot. Drag with a mouse or use left and right arrow keys to turn. Press W to wave."></canvas></div><div class="scene-controls"><button id="motion-toggle" aria-pressed="false">Pause motion</button><button id="explode-toggle">Say hello ${arrow}</button></div></div></div><div class="discipline-list">${disciplines.map((d,i)=>`<a class="discipline-row reveal" href="/team/#${d.id}"><span class="discipline-icon">${icon(d.id)}</span><div><h3>${d.name}</h3><p>${d.line}</p></div>${arrow}</a>`).join('')}</div></div></section>
    <section class="season-section"><div class="section-inner season-inner"><div class="reveal"><span class="section-kicker">2026–2027 season</span><h2>The BIOBUZZ<br>season.</h2><p>Follow our journey through BIOBUZZ™ presented by RTX.</p><a class="text-link" href="https://www.firstinspires.org/programs/ftc/game-and-season" target="_blank" rel="noreferrer">Explore the game ${arrow}</a></div><div class="season-art reveal"><img src="/assets/biobuzz-official.png" width="1726" height="1227" alt="BIOBUZZ presented by RTX" loading="lazy" decoding="async"/></div></div></section>
    <section class="section events-preview"><div class="section-inner"><div class="section-heading reveal"><div><span class="section-kicker">On the calendar</span><h2>See what’s next.</h2></div><a class="text-link" href="/events/">All events ${arrow}</a></div><div class="event-list" data-events="preview">${loadingEvents}</div></div></section>${contactCTA}</main>${eventDialog}`
  },
  team:{title:'Our team · EDIT Saffron',description:'Meet the students who make EDIT Saffron, FTC Team 22310 at Lo-Ellen Park Secondary School in Greater Sudbury.',type:'AboutPage',body:`<main id="main"><header class="page-heading"><span class="section-kicker">Lo-Ellen Park · FTC 22310</span><h1>Meet Saffron.</h1><p>Meet the students who design, build, program, and promote our FIRST Tech Challenge robots.</p><nav class="discipline-jump" aria-label="Team disciplines">${disciplines.map(d=>`<a href="#${d.id}">${d.name} <span aria-hidden="true">↓</span></a>`).join('')}</nav></header><div class="team-disciplines section-inner">${disciplines.map((d,i)=>`<section id="${d.id}" class="team-discipline reveal"><div class="discipline-heading"><span class="discipline-icon">${icon(d.id)}</span><h2>${d.name}</h2><p>${d.description}</p></div><div class="member-list">${d.people.map(name=>`<article class="member"><span class="member-avatar" aria-hidden="true">${name.split(' ').map(x=>x[0]).join('')}</span><h3>${name}</h3></article>`).join('')}</div></section>`).join('')}</div>${contactCTA}</main>`},
  events:{title:'Events · EDIT Saffron',description:'Follow the EDIT Saffron FTC Team 22310 calendar for robotics meetings, practices, outreach, and competitions in Greater Sudbury.',type:'CollectionPage',body:`<main id="main"><header class="page-heading"><span class="section-kicker">Team calendar · FTC 22310</span><h1>Coming up.</h1><p>Browse our public schedule for robotics meetings, build practices, outreach, and FIRST Tech Challenge competitions in Greater Sudbury.</p></header><section class="calendar-section section-inner"><div class="calendar-toolbar"><div class="calendar-view" role="group" aria-label="Calendar view"><button data-view="agenda" aria-pressed="true">List</button><button data-view="month" aria-pressed="false">Month</button></div><label><span class="sr-only">Event category</span><select id="event-category"><option value="all">All events</option><option value="competition">Competitions</option><option value="outreach">Outreach</option><option value="practice">Practice</option><option value="meeting">Meetings</option><option value="other">Other</option></select></label><p class="calendar-timezone">Toronto time</p></div><div id="month-controls" class="calendar-month-header" hidden><h2 id="month-title"></h2><div><button id="previous-month" aria-label="Previous month">←</button><button id="today-month">Today</button><button id="next-month" aria-label="Next month">→</button></div></div><div class="event-list" data-events="all">${loadingEvents}</div><p class="calendar-status" id="calendar-status" role="status"></p></section>${contactCTA}</main>${eventDialog}`},
  contact:{title:'Contact · EDIT Saffron',description:'Contact EDIT Saffron, FTC Team 22310 in Greater Sudbury, Ontario about outreach, robotics, sponsorship, or collaboration.',type:'ContactPage',body:`<main id="main"><header class="page-heading"><span class="section-kicker">Contact the team · FTC 22310</span><h1>Say hello.</h1><p>Ask about our student-built robots, community outreach, sponsorship, or a collaboration with the team.</p></header><div class="contact-layout section-inner"><aside class="contact-aside"><a class="contact-email" href="mailto:team@22310.ca">team@22310.ca ${arrow}</a><p>Lo-Ellen Park Secondary School<br>Greater Sudbury, Ontario</p><a class="text-link" href="https://team.22310.ca">Team workspace ${arrow}</a><img class="contact-flower" src="/assets/saffron-logo-2026.png?v=1" width="140" height="140" alt=""/></aside><form class="contact-form" id="contact-form"><div class="form-two"><label>Name<input name="name" autocomplete="name" required maxlength="80" placeholder="Your name"/></label><label>Email<input name="email" type="email" autocomplete="email" required maxlength="254" placeholder="you@example.com"/></label></div><label>Topic<select name="subject" required><option value="">Choose a topic</option><option>Partnership or sponsorship</option><option>Outreach or collaboration</option><option>Robotics question</option><option>Something else</option></select></label><label>Message<textarea name="message" required minlength="10" maxlength="5000" placeholder="What’s on your mind?"></textarea></label><div class="honeypot" aria-hidden="true"><label>Leave this empty<input name="website" tabindex="-1" autocomplete="off"/></label></div><div class="contact-form-footer"><button type="submit" class="button">Send message ${arrow}</button><span>Your message goes to our team.</span></div><p id="contact-message" class="contact-message" role="status" aria-live="polite"></p><details class="privacy-note"><summary>About this form</summary><p>Your name, email, and message are shared with the team. A necessary cookie limits messages to three per hour, with additional spam protection.</p></details><noscript><p>Email us at <a href="mailto:team@22310.ca">team@22310.ca</a>.</p></noscript></form></div></main>`},
  '404':{title:'Page not found · EDIT Saffron',description:'Find your way back to EDIT Saffron.',type:'WebPage',body:`<main id="main" class="not-found"><img src="/assets/saffron-logo-2026.png?v=1" width="80" height="80" alt=""/><span class="section-kicker">404</span><h1>A little off course.</h1><p>That page isn’t here. Let’s get you back to the team.</p><a class="button" href="/">Back home ${arrow}</a></main>`}
};
